---
- hosts: dev
  become: True
  tasks:

    - name: Get if any container running
      docker_container_info:
        name: {{RUNNING_TAG}}
      register: Status

    - name: Stop container if it is running
      docker_container:
        name: {{RUNNING_TAG}}
        state: stopped
        when: Status.container.Status == "running"

    - name: Start the container
      docker_container:
        name: {{DOCKER_TAG}}
        image: "muktarbek/ems:{{DOCKER_TAG}}"
        state: started
        pull: true
        published_ports:
          - 0.0.0.0:8080:8080
