---
- hosts: dev
  become: True
  vars:
    docker_volume: db_data
    db_name: ems
  tasks:
    - name: Get DB info
      docker_container_info:
        name: "{{ db_name }}"
      register: result

    - name: Run command when mysql not exist or not running
      docker_container:
          name: "{{ db_name }}"
          image: mysql:8.0.27
          volumes:
            - "{{ docker_volume }}:/var/lib/mysql:rw"
          restart: true
          env:
            MYSQL_ROOT_PASSWORD: 123123
            MYSQL_DATABASE: ems
            MYSQL_USER: airmanas
            MYSQL_PASSWORD: 123123
      when: not result.exists


